Solution
mate-academy/layout_colored-blocks pull request #378
Opened 2020-04-21 11:33 UTC by ogsevko

- [DEMO LINK](https://ogsevko.github.io/layout_colored-blocks/)

- [TEST REPORT LINK](https://ogsevko.github.io/layout_colored-blocks/report/html_report/)

2020-04-21 13:18 UTC, irenhh requested changes

2020-04-21 13:18 UTC, irenhh commented on src/index.html
> +  <div id="b01"></div>
use class names that describe the content or behavior of the data, abstract names are a bad practice

2020-04-21 13:18 UTC, irenhh commented on src/style.css
> +div {
create a general class name for this purpose

2020-04-21 13:18 UTC, irenhh commented on src/index.html
> +  <div id="b01"></div>
ids are not recommended for styling elements, they have high specificity and they can't be reused,
use class names instead

2020-04-21 15:18 UTC, irenhh requested changes

2020-04-21 15:18 UTC, irenhh commented on src/style.css
> +}
class names are very bad, I don't understand your shortened names, the same will happen if any other developer decides to look up something in your code. You need to give specific and clear names

2020-04-22 06:41 UTC, irenhh requested changes
you didn't fix your code

2020-04-22 06:52 UTC, ogsevko commented
I did fix it. I don't know why it's not visible in this thread though. [Here](https://github.com/mate-academy/layout_colored-blocks/commit/fa19a4d2337b64d9f61b826da7c58d226f628078 ) is my last commit.

2020-04-22 13:18 UTC, irenhh approved these changes
not it's fixed :)

2023-12-26 21:52 UTC, closed without merging